# Generated by Django 4.0.5 on 2022-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='telephone',
            field=models.CharField(default=998, max_length=255),
        ),
    ]
