# Generated by Django 4.0.5 on 2022-07-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_farmers_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmers',
            options={'verbose_name_plural': 'Farmers'},
        ),
        migrations.AlterModelOptions(
            name='fruits',
            options={'verbose_name_plural': 'Fruits'},
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='kg',
        ),
        migrations.RemoveField(
            model_name='fruits',
            name='price',
        ),
        migrations.AddField(
            model_name='farmers',
            name='kg',
            field=models.CharField(blank=True, default=998, max_length=255),
        ),
        migrations.AddField(
            model_name='farmers',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='farmers',
            name='price',
            field=models.CharField(blank=True, default=998, max_length=255),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmers'),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
